---
title: "DnD"
author: "Nathan Lam"
date: "4/10/2021"
output: pdf_document
---

```{r}
library(dnddata)
library(pls)
library(glmnet) #
library(stringr)
library(randomForest)

```




```{r}
spell_list <- read.csv("spells.csv")
pick <- c(2,4,7,9,12,14,21,22,24,25,26,30)
remove <- -c(1,3,5,6,8,10,11,13,15,16,17,18,19,20,21,22,23,27,28,29,31,32)
colnames(spell_list)
spell_list[,remove]
```

```{r cast time}
# converting casting time into seconds
# actions, bonus actions, and reations are labeled as 6 seconds each
#     even though you can do all 3 within 6 seconds (1 turn)

#converting castng time into seconds
spell_list$Casting.Time[spell_list$name == "Poison Spray"] <- 6 #uniquely has a NA

#variables that contain "word" and turn them into seconds

spell_list$Casting.Time[str_detect(spell_list$Casting.Time, "action")] <- as.numeric(str_extract(spell_list$Casting.Time[str_detect(spell_list$Casting.Time, "action")],"[0-9]+"))*6

#variables that contain "action", extract the number*6
spell_list$Casting.Time[str_detect(spell_list$Casting.Time, "Bonus Action")] <- as.numeric(str_extract(spell_list$Casting.Time[str_detect(spell_list$Casting.Time, "Bonus Action")],"[0-9]+"))*6

#variables that contain "minute", extract the number*60
spell_list$Casting.Time[str_detect(spell_list$Casting.Time, "minute")] <- as.numeric(str_extract(spell_list$Casting.Time[str_detect(spell_list$Casting.Time, "minute")],"[0-9]+")) * 60

#variables that contain "hour", extract the number*60
spell_list$Casting.Time[str_detect(spell_list$Casting.Time, "hour")] <- as.numeric(str_extract(spell_list$Casting.Time[str_detect(spell_list$Casting.Time, "hour")],"[0-9]+")) * 60 * 60
```

```{r avg dmg}
#deriving average damage from damage dice

#calculating average damage
avg.dmg <- (as.numeric(str_extract(spell_list$Damage,"[0-9]+$")) + 1)/2
avg.dmg <- avg.dmg*(as.numeric(str_extract(spell_list$Damage,"^[0-9]+")))
avg.dmg[is.na(avg.dmg)] <- 0


avg.2dmg <- (as.numeric(str_extract(spell_list$Secondary.Damage,"[0-9]+$")) + 1)/2
avg.2dmg <- avg.2dmg*(as.numeric(str_extract(spell_list$Secondary.Damage,"^[0-9]+")))
avg.2dmg[is.na(avg.2dmg)] <- 0


spell_list$Damage <- avg.dmg+avg.2dmg


# healing
avg.healing <- (as.numeric(str_extract(spell_list$Healing,"(?<=d)[0-9]+"))+1)/2
avg.healing <- avg.healing*as.numeric(str_extract(spell_list$Healing,"^[0-9]+"))
avg.healing[is.na(avg.healing)] <- 0

heal_const <- as.numeric(str_extract(spell_list$Healing,"(?<!d)[0-9]+$"))
heal_const[is.na(heal_const)] <- 0

spell_list$Healing <- avg.healing + heal_const


```

```{r duration}
# converting duration into seconds, using the max possible duration
# instantaneous = 1 second
# 1 round = 60 seconds
# undetermined durations are set as 1 year or 365*24*60*60 seconds

spell_list$Duration <- tolower(spell_list$Duration)

spell_list$Duration[str_detect(spell_list$Duration, "Instantaneous")] <- 1 

spell_list$Duration[str_detect(spell_list$Duration, "round")] <- as.numeric(str_extract(spell_list$Duration[str_detect(spell_list$Duration, "round")],"[0-9]+")) * 60

spell_list$Duration[str_detect(spell_list$Duration, "minute")] <- as.numeric(str_extract(spell_list$Duration[str_detect(spell_list$Duration, "minute")],"[0-9]+")) * 60

spell_list$Duration[str_detect(spell_list$Duration, "hour")] <- as.numeric(str_extract(spell_list$Duration[str_detect(spell_list$Duration, "hour")],"[0-9]+")) * 60 * 60

spell_list$Duration[str_detect(spell_list$Duration, "day")] <- 
  as.numeric(str_extract(spell_list$Duration[str_detect(spell_list$Duration, "day")],"[0-9]+")) * 60 * 60 * 24

spell_list$Duration[str_detect(spell_list$Duration, "dispelled")] <- 365*24*60*60
spell_list$Duration[str_detect(spell_list$Duration, "special")] <- 365*24*60*60

```

```{r range}
# converting range to feet
# self is range 0
# sight is 100 miles
# special and unlimited is half the earth's circumference 

spell_list$Range <- tolower(spell_list$Range)


spell_list$Range[str_detect(spell_list$Range, "self")] <- 0
spell_list$Range[str_detect(spell_list$Range, "touch")] <- 2
spell_list$Range[str_detect(spell_list$Range, "sight")] <- 100 * 5280
spell_list$Range[str_detect(spell_list$Range, "special")] <- 12450 * 5280
spell_list$Range[str_detect(spell_list$Range, "unlimited")] <- 12450 * 5280


spell_list$Range[str_detect(spell_list$Range, "ft")] <- as.numeric(str_extract(spell_list$Range[str_detect(spell_list$Range, "ft")],"[0-9]+"))
spell_list$Range[str_detect(spell_list$Range, "feet")] <- as.numeric(str_extract(spell_list$Range[str_detect(spell_list$Range, "feet")],"[0-9]+"))
  
spell_list$Range[str_detect(spell_list$Range, "mile")] <- as.numeric(str_extract(spell_list$Range[str_detect(spell_list$Range, "mile")],"[0-9]+")) * 5280


```

```{r ritual and conc}
#turning ritual and concentration into booleans
spell_list$Ritual <- tolower(spell_list$Ritual)
spell_list$Concentration <- tolower(spell_list$Concentration)


spell_list$Ritual[spell_list$Ritual == "yes"] <- 1
spell_list$Ritual[is.na(spell_list$Ritual)] <- 0

spell_list$Concentration[spell_list$Concentration == "yes"] <- 1
spell_list$Concentration[is.na(spell_list$Concentration)] <- 0


unique(spell_list$Concentration)
```

```{r}
write.csv(spell_list[,c(-2,remove,-26)],"spells_cleaned.csv",row.names = F)
spells <- read.csv("spells_cleaned.csv")
spells$Duration <- as.numeric(spells$Duration)
spells$Concentration <- as.numeric(spells$Concentration)
spells


levels <- lm(Level~. ,data=spells)
summary(levels)


```




